# ps7_params.tcl - Zynq PS7 configuration of the EBAZ4205 board, as CONFIG.* for processing_system7 5.5.
# Only the values that differ from the IP defaults are listed (DDR3 MT41K128M16 16-bit, MIO map, UART1,
# SD0, NAND, ENET0 over EMIO, TTC0, clocks). They are the PS settings of the hardware handoff the BSP
# workspace was originally built from; make_xsa.tcl applies them in one set_property -dict, the way a
# board preset is applied. The PL side of the design is irrelevant for the BSP and is not recreated.
set PS7_PARAMS {
  CONFIG.PCW_DDR_RAM_HIGHADDR 0x0FFFFFFF
  CONFIG.PCW_UIPARAM_DDR_T_FAW 40.0
  CONFIG.PCW_FPGA0_PERIPHERAL_FREQMHZ 25
  CONFIG.PCW_FPGA1_PERIPHERAL_FREQMHZ 25
  CONFIG.PCW_FPGA2_PERIPHERAL_FREQMHZ 25
  CONFIG.PCW_FPGA3_PERIPHERAL_FREQMHZ 25
  CONFIG.PCW_ACT_SMC_PERIPHERAL_FREQMHZ 100.000000
  CONFIG.PCW_ACT_ENET0_PERIPHERAL_FREQMHZ 25.000000
  CONFIG.PCW_ACT_SDIO_PERIPHERAL_FREQMHZ 100.000000
  CONFIG.PCW_ACT_UART_PERIPHERAL_FREQMHZ 100.000000
  CONFIG.PCW_ACT_FPGA0_PERIPHERAL_FREQMHZ 25.000000
  CONFIG.PCW_CLK0_FREQ 25000000
  CONFIG.PCW_SMC_PERIPHERAL_DIVISOR0 16
  CONFIG.PCW_SDIO_PERIPHERAL_DIVISOR0 16
  CONFIG.PCW_UART_PERIPHERAL_DIVISOR0 16
  CONFIG.PCW_FCLK0_PERIPHERAL_DIVISOR1 8
  CONFIG.PCW_ENET0_PERIPHERAL_DIVISOR1 5
  CONFIG.PCW_SMC_PERIPHERAL_VALID 1
  CONFIG.PCW_SDIO_PERIPHERAL_VALID 1
  CONFIG.PCW_UART_PERIPHERAL_VALID 1
  CONFIG.PCW_EN_EMIO_ENET0 1
  CONFIG.PCW_EN_EMIO_GPIO 1
  CONFIG.PCW_EN_EMIO_TTC0 1
  CONFIG.PCW_GPIO_EMIO_GPIO_WIDTH 1
  CONFIG.PCW_EN_SMC 1
  CONFIG.PCW_EN_ENET0 1
  CONFIG.PCW_EN_GPIO 1
  CONFIG.PCW_EN_SDIO0 1
  CONFIG.PCW_EN_UART1 1
  CONFIG.PCW_EN_TTC0 1
  CONFIG.PCW_UIPARAM_DDR_BUS_WIDTH {16 Bit}
  CONFIG.PCW_UIPARAM_DDR_PARTNO {MT41K128M16 JT-125}
  CONFIG.PCW_UIPARAM_DDR_DRAM_WIDTH {16 Bits}
  CONFIG.PCW_UIPARAM_DDR_DEVICE_CAPACITY {2048 MBits}
  CONFIG.PCW_DDR_PRIORITY_WRITEPORT_0 {<Select>}
  CONFIG.PCW_DDR_PRIORITY_WRITEPORT_1 {<Select>}
  CONFIG.PCW_DDR_PRIORITY_WRITEPORT_2 {<Select>}
  CONFIG.PCW_DDR_PRIORITY_WRITEPORT_3 {<Select>}
  CONFIG.PCW_DDR_PRIORITY_READPORT_0 {<Select>}
  CONFIG.PCW_DDR_PRIORITY_READPORT_1 {<Select>}
  CONFIG.PCW_DDR_PRIORITY_READPORT_2 {<Select>}
  CONFIG.PCW_DDR_PRIORITY_READPORT_3 {<Select>}
  CONFIG.PCW_NAND_PERIPHERAL_ENABLE 1
  CONFIG.PCW_NAND_NAND_IO {MIO 0 2.. 14}
  CONFIG.PCW_NAND_GRP_D8_IO {<Select>}
  CONFIG.PCW_NOR_NOR_IO {<Select>}
  CONFIG.PCW_NOR_GRP_A25_IO {<Select>}
  CONFIG.PCW_NOR_GRP_CS0_IO {<Select>}
  CONFIG.PCW_NOR_GRP_SRAM_CS0_IO {<Select>}
  CONFIG.PCW_NOR_GRP_CS1_IO {<Select>}
  CONFIG.PCW_NOR_GRP_SRAM_CS1_IO {<Select>}
  CONFIG.PCW_NOR_GRP_SRAM_INT_IO {<Select>}
  CONFIG.PCW_QSPI_QSPI_IO {<Select>}
  CONFIG.PCW_QSPI_GRP_SINGLE_SS_IO {<Select>}
  CONFIG.PCW_QSPI_GRP_SS1_IO {<Select>}
  CONFIG.PCW_SINGLE_QSPI_DATA_MODE {<Select>}
  CONFIG.PCW_DUAL_STACK_QSPI_DATA_MODE {<Select>}
  CONFIG.PCW_DUAL_PARALLEL_QSPI_DATA_MODE {<Select>}
  CONFIG.PCW_QSPI_GRP_IO1_IO {<Select>}
  CONFIG.PCW_QSPI_GRP_FBCLK_IO {<Select>}
  CONFIG.PCW_ENET0_PERIPHERAL_ENABLE 1
  CONFIG.PCW_ENET0_ENET0_IO EMIO
  CONFIG.PCW_ENET0_GRP_MDIO_ENABLE 1
  CONFIG.PCW_ENET0_GRP_MDIO_IO EMIO
  CONFIG.PCW_ENET_RESET_SELECT {<Select>}
  CONFIG.PCW_ENET0_RESET_IO {<Select>}
  CONFIG.PCW_ENET1_ENET1_IO {<Select>}
  CONFIG.PCW_ENET1_GRP_MDIO_IO {<Select>}
  CONFIG.PCW_ENET1_RESET_IO {<Select>}
  CONFIG.PCW_SD0_PERIPHERAL_ENABLE 1
  CONFIG.PCW_SD0_SD0_IO {MIO 40 .. 45}
  CONFIG.PCW_SD0_GRP_CD_IO {<Select>}
  CONFIG.PCW_SD0_GRP_WP_IO {<Select>}
  CONFIG.PCW_SD0_GRP_POW_IO {<Select>}
  CONFIG.PCW_SD1_SD1_IO {<Select>}
  CONFIG.PCW_SD1_GRP_CD_IO {<Select>}
  CONFIG.PCW_SD1_GRP_WP_IO {<Select>}
  CONFIG.PCW_SD1_GRP_POW_IO {<Select>}
  CONFIG.PCW_UART0_UART0_IO {<Select>}
  CONFIG.PCW_UART0_GRP_FULL_IO {<Select>}
  CONFIG.PCW_UART1_PERIPHERAL_ENABLE 1
  CONFIG.PCW_UART1_UART1_IO {MIO 24 .. 25}
  CONFIG.PCW_UART1_GRP_FULL_IO {<Select>}
  CONFIG.PCW_SPI0_SPI0_IO {<Select>}
  CONFIG.PCW_SPI0_GRP_SS0_IO {<Select>}
  CONFIG.PCW_SPI0_GRP_SS1_IO {<Select>}
  CONFIG.PCW_SPI0_GRP_SS2_IO {<Select>}
  CONFIG.PCW_SPI1_SPI1_IO {<Select>}
  CONFIG.PCW_SPI1_GRP_SS0_IO {<Select>}
  CONFIG.PCW_SPI1_GRP_SS1_IO {<Select>}
  CONFIG.PCW_SPI1_GRP_SS2_IO {<Select>}
  CONFIG.PCW_CAN0_CAN0_IO {<Select>}
  CONFIG.PCW_CAN0_GRP_CLK_IO {<Select>}
  CONFIG.PCW_CAN1_CAN1_IO {<Select>}
  CONFIG.PCW_CAN1_GRP_CLK_IO {<Select>}
  CONFIG.PCW_TRACE_TRACE_IO {<Select>}
  CONFIG.PCW_TRACE_GRP_2BIT_IO {<Select>}
  CONFIG.PCW_TRACE_GRP_4BIT_IO {<Select>}
  CONFIG.PCW_TRACE_GRP_8BIT_IO {<Select>}
  CONFIG.PCW_TRACE_GRP_16BIT_IO {<Select>}
  CONFIG.PCW_TRACE_GRP_32BIT_IO {<Select>}
  CONFIG.PCW_WDT_WDT_IO {<Select>}
  CONFIG.PCW_TTC0_PERIPHERAL_ENABLE 1
  CONFIG.PCW_TTC0_TTC0_IO EMIO
  CONFIG.PCW_TTC1_TTC1_IO {<Select>}
  CONFIG.PCW_PJTAG_PJTAG_IO {<Select>}
  CONFIG.PCW_USB0_USB0_IO {<Select>}
  CONFIG.PCW_USB_RESET_SELECT {<Select>}
  CONFIG.PCW_USB0_RESET_IO {<Select>}
  CONFIG.PCW_USB1_USB1_IO {<Select>}
  CONFIG.PCW_USB1_RESET_IO {<Select>}
  CONFIG.PCW_I2C0_I2C0_IO {<Select>}
  CONFIG.PCW_I2C0_GRP_INT_IO {<Select>}
  CONFIG.PCW_I2C0_RESET_IO {<Select>}
  CONFIG.PCW_I2C1_I2C1_IO {<Select>}
  CONFIG.PCW_I2C1_GRP_INT_IO {<Select>}
  CONFIG.PCW_I2C_RESET_SELECT {<Select>}
  CONFIG.PCW_I2C1_RESET_IO {<Select>}
  CONFIG.PCW_GPIO_MIO_GPIO_ENABLE 1
  CONFIG.PCW_GPIO_MIO_GPIO_IO MIO
  CONFIG.PCW_GPIO_EMIO_GPIO_ENABLE 1
  CONFIG.PCW_GPIO_EMIO_GPIO_IO 1
  CONFIG.PCW_ENET0_PERIPHERAL_FREQMHZ {100 Mbps}
  CONFIG.PCW_ENET0_PERIPHERAL_CLKSRC External
  CONFIG.PCW_MIO_0_PULLUP enabled
  CONFIG.PCW_MIO_0_IOTYPE {LVCMOS 3.3V}
  CONFIG.PCW_MIO_0_DIRECTION out
  CONFIG.PCW_MIO_0_SLEW slow
  CONFIG.PCW_MIO_1_PULLUP enabled
  CONFIG.PCW_MIO_1_IOTYPE {LVCMOS 3.3V}
  CONFIG.PCW_MIO_1_DIRECTION inout
  CONFIG.PCW_MIO_1_SLEW slow
  CONFIG.PCW_MIO_2_PULLUP disabled
  CONFIG.PCW_MIO_2_IOTYPE {LVCMOS 3.3V}
  CONFIG.PCW_MIO_2_DIRECTION out
  CONFIG.PCW_MIO_2_SLEW slow
  CONFIG.PCW_MIO_3_PULLUP disabled
  CONFIG.PCW_MIO_3_IOTYPE {LVCMOS 3.3V}
  CONFIG.PCW_MIO_3_DIRECTION out
  CONFIG.PCW_MIO_3_SLEW slow
  CONFIG.PCW_MIO_4_PULLUP disabled
  CONFIG.PCW_MIO_4_IOTYPE {LVCMOS 3.3V}
  CONFIG.PCW_MIO_4_DIRECTION inout
  CONFIG.PCW_MIO_4_SLEW slow
  CONFIG.PCW_MIO_5_PULLUP disabled
  CONFIG.PCW_MIO_5_IOTYPE {LVCMOS 3.3V}
  CONFIG.PCW_MIO_5_DIRECTION inout
  CONFIG.PCW_MIO_5_SLEW slow
  CONFIG.PCW_MIO_6_PULLUP disabled
  CONFIG.PCW_MIO_6_IOTYPE {LVCMOS 3.3V}
  CONFIG.PCW_MIO_6_DIRECTION inout
  CONFIG.PCW_MIO_6_SLEW slow
  CONFIG.PCW_MIO_7_PULLUP disabled
  CONFIG.PCW_MIO_7_IOTYPE {LVCMOS 3.3V}
  CONFIG.PCW_MIO_7_DIRECTION out
  CONFIG.PCW_MIO_7_SLEW slow
  CONFIG.PCW_MIO_8_PULLUP disabled
  CONFIG.PCW_MIO_8_IOTYPE {LVCMOS 3.3V}
  CONFIG.PCW_MIO_8_DIRECTION out
  CONFIG.PCW_MIO_8_SLEW slow
  CONFIG.PCW_MIO_9_PULLUP enabled
  CONFIG.PCW_MIO_9_IOTYPE {LVCMOS 3.3V}
  CONFIG.PCW_MIO_9_DIRECTION inout
  CONFIG.PCW_MIO_9_SLEW slow
  CONFIG.PCW_MIO_10_PULLUP enabled
  CONFIG.PCW_MIO_10_IOTYPE {LVCMOS 3.3V}
  CONFIG.PCW_MIO_10_DIRECTION inout
  CONFIG.PCW_MIO_10_SLEW slow
  CONFIG.PCW_MIO_11_PULLUP enabled
  CONFIG.PCW_MIO_11_IOTYPE {LVCMOS 3.3V}
  CONFIG.PCW_MIO_11_DIRECTION inout
  CONFIG.PCW_MIO_11_SLEW slow
  CONFIG.PCW_MIO_12_PULLUP enabled
  CONFIG.PCW_MIO_12_IOTYPE {LVCMOS 3.3V}
  CONFIG.PCW_MIO_12_DIRECTION inout
  CONFIG.PCW_MIO_12_SLEW slow
  CONFIG.PCW_MIO_13_PULLUP enabled
  CONFIG.PCW_MIO_13_IOTYPE {LVCMOS 3.3V}
  CONFIG.PCW_MIO_13_DIRECTION inout
  CONFIG.PCW_MIO_13_SLEW slow
  CONFIG.PCW_MIO_14_PULLUP enabled
  CONFIG.PCW_MIO_14_IOTYPE {LVCMOS 3.3V}
  CONFIG.PCW_MIO_14_DIRECTION in
  CONFIG.PCW_MIO_14_SLEW slow
  CONFIG.PCW_MIO_15_PULLUP enabled
  CONFIG.PCW_MIO_15_IOTYPE {LVCMOS 3.3V}
  CONFIG.PCW_MIO_15_DIRECTION inout
  CONFIG.PCW_MIO_15_SLEW slow
  CONFIG.PCW_MIO_16_PULLUP enabled
  CONFIG.PCW_MIO_16_IOTYPE {LVCMOS 3.3V}
  CONFIG.PCW_MIO_16_DIRECTION inout
  CONFIG.PCW_MIO_16_SLEW slow
  CONFIG.PCW_MIO_17_PULLUP enabled
  CONFIG.PCW_MIO_17_IOTYPE {LVCMOS 3.3V}
  CONFIG.PCW_MIO_17_DIRECTION inout
  CONFIG.PCW_MIO_17_SLEW slow
  CONFIG.PCW_MIO_18_PULLUP enabled
  CONFIG.PCW_MIO_18_IOTYPE {LVCMOS 3.3V}
  CONFIG.PCW_MIO_18_DIRECTION inout
  CONFIG.PCW_MIO_18_SLEW slow
  CONFIG.PCW_MIO_19_PULLUP enabled
  CONFIG.PCW_MIO_19_IOTYPE {LVCMOS 3.3V}
  CONFIG.PCW_MIO_19_DIRECTION inout
  CONFIG.PCW_MIO_19_SLEW slow
  CONFIG.PCW_MIO_20_PULLUP enabled
  CONFIG.PCW_MIO_20_IOTYPE {LVCMOS 3.3V}
  CONFIG.PCW_MIO_20_DIRECTION inout
  CONFIG.PCW_MIO_20_SLEW slow
  CONFIG.PCW_MIO_21_PULLUP enabled
  CONFIG.PCW_MIO_21_IOTYPE {LVCMOS 3.3V}
  CONFIG.PCW_MIO_21_DIRECTION inout
  CONFIG.PCW_MIO_21_SLEW slow
  CONFIG.PCW_MIO_22_PULLUP enabled
  CONFIG.PCW_MIO_22_IOTYPE {LVCMOS 3.3V}
  CONFIG.PCW_MIO_22_DIRECTION inout
  CONFIG.PCW_MIO_22_SLEW slow
  CONFIG.PCW_MIO_23_PULLUP enabled
  CONFIG.PCW_MIO_23_IOTYPE {LVCMOS 3.3V}
  CONFIG.PCW_MIO_23_DIRECTION inout
  CONFIG.PCW_MIO_23_SLEW slow
  CONFIG.PCW_MIO_24_PULLUP enabled
  CONFIG.PCW_MIO_24_IOTYPE {LVCMOS 3.3V}
  CONFIG.PCW_MIO_24_DIRECTION out
  CONFIG.PCW_MIO_24_SLEW slow
  CONFIG.PCW_MIO_25_PULLUP enabled
  CONFIG.PCW_MIO_25_IOTYPE {LVCMOS 3.3V}
  CONFIG.PCW_MIO_25_DIRECTION in
  CONFIG.PCW_MIO_25_SLEW slow
  CONFIG.PCW_MIO_26_PULLUP enabled
  CONFIG.PCW_MIO_26_IOTYPE {LVCMOS 3.3V}
  CONFIG.PCW_MIO_26_DIRECTION inout
  CONFIG.PCW_MIO_26_SLEW slow
  CONFIG.PCW_MIO_27_PULLUP enabled
  CONFIG.PCW_MIO_27_IOTYPE {LVCMOS 3.3V}
  CONFIG.PCW_MIO_27_DIRECTION inout
  CONFIG.PCW_MIO_27_SLEW slow
  CONFIG.PCW_MIO_28_PULLUP enabled
  CONFIG.PCW_MIO_28_IOTYPE {LVCMOS 3.3V}
  CONFIG.PCW_MIO_28_DIRECTION inout
  CONFIG.PCW_MIO_28_SLEW slow
  CONFIG.PCW_MIO_29_PULLUP enabled
  CONFIG.PCW_MIO_29_IOTYPE {LVCMOS 3.3V}
  CONFIG.PCW_MIO_29_DIRECTION inout
  CONFIG.PCW_MIO_29_SLEW slow
  CONFIG.PCW_MIO_30_PULLUP enabled
  CONFIG.PCW_MIO_30_IOTYPE {LVCMOS 3.3V}
  CONFIG.PCW_MIO_30_DIRECTION inout
  CONFIG.PCW_MIO_30_SLEW slow
  CONFIG.PCW_MIO_31_PULLUP enabled
  CONFIG.PCW_MIO_31_IOTYPE {LVCMOS 3.3V}
  CONFIG.PCW_MIO_31_DIRECTION inout
  CONFIG.PCW_MIO_31_SLEW slow
  CONFIG.PCW_MIO_32_PULLUP enabled
  CONFIG.PCW_MIO_32_IOTYPE {LVCMOS 3.3V}
  CONFIG.PCW_MIO_32_DIRECTION inout
  CONFIG.PCW_MIO_32_SLEW slow
  CONFIG.PCW_MIO_33_PULLUP enabled
  CONFIG.PCW_MIO_33_IOTYPE {LVCMOS 3.3V}
  CONFIG.PCW_MIO_33_DIRECTION inout
  CONFIG.PCW_MIO_33_SLEW slow
  CONFIG.PCW_MIO_34_PULLUP enabled
  CONFIG.PCW_MIO_34_IOTYPE {LVCMOS 3.3V}
  CONFIG.PCW_MIO_34_DIRECTION in
  CONFIG.PCW_MIO_34_SLEW slow
  CONFIG.PCW_MIO_35_PULLUP enabled
  CONFIG.PCW_MIO_35_IOTYPE {LVCMOS 3.3V}
  CONFIG.PCW_MIO_35_DIRECTION inout
  CONFIG.PCW_MIO_35_SLEW slow
  CONFIG.PCW_MIO_36_PULLUP enabled
  CONFIG.PCW_MIO_36_IOTYPE {LVCMOS 3.3V}
  CONFIG.PCW_MIO_36_DIRECTION inout
  CONFIG.PCW_MIO_36_SLEW slow
  CONFIG.PCW_MIO_37_PULLUP enabled
  CONFIG.PCW_MIO_37_IOTYPE {LVCMOS 3.3V}
  CONFIG.PCW_MIO_37_DIRECTION inout
  CONFIG.PCW_MIO_37_SLEW slow
  CONFIG.PCW_MIO_38_PULLUP enabled
  CONFIG.PCW_MIO_38_IOTYPE {LVCMOS 3.3V}
  CONFIG.PCW_MIO_38_DIRECTION inout
  CONFIG.PCW_MIO_38_SLEW slow
  CONFIG.PCW_MIO_39_PULLUP enabled
  CONFIG.PCW_MIO_39_IOTYPE {LVCMOS 3.3V}
  CONFIG.PCW_MIO_39_DIRECTION inout
  CONFIG.PCW_MIO_39_SLEW slow
  CONFIG.PCW_MIO_40_PULLUP enabled
  CONFIG.PCW_MIO_40_IOTYPE {LVCMOS 3.3V}
  CONFIG.PCW_MIO_40_DIRECTION inout
  CONFIG.PCW_MIO_40_SLEW slow
  CONFIG.PCW_MIO_41_PULLUP enabled
  CONFIG.PCW_MIO_41_IOTYPE {LVCMOS 3.3V}
  CONFIG.PCW_MIO_41_DIRECTION inout
  CONFIG.PCW_MIO_41_SLEW slow
  CONFIG.PCW_MIO_42_PULLUP enabled
  CONFIG.PCW_MIO_42_IOTYPE {LVCMOS 3.3V}
  CONFIG.PCW_MIO_42_DIRECTION inout
  CONFIG.PCW_MIO_42_SLEW slow
  CONFIG.PCW_MIO_43_PULLUP enabled
  CONFIG.PCW_MIO_43_IOTYPE {LVCMOS 3.3V}
  CONFIG.PCW_MIO_43_DIRECTION inout
  CONFIG.PCW_MIO_43_SLEW slow
  CONFIG.PCW_MIO_44_PULLUP enabled
  CONFIG.PCW_MIO_44_IOTYPE {LVCMOS 3.3V}
  CONFIG.PCW_MIO_44_DIRECTION inout
  CONFIG.PCW_MIO_44_SLEW slow
  CONFIG.PCW_MIO_45_PULLUP enabled
  CONFIG.PCW_MIO_45_IOTYPE {LVCMOS 3.3V}
  CONFIG.PCW_MIO_45_DIRECTION inout
  CONFIG.PCW_MIO_45_SLEW slow
  CONFIG.PCW_MIO_46_PULLUP enabled
  CONFIG.PCW_MIO_46_IOTYPE {LVCMOS 3.3V}
  CONFIG.PCW_MIO_46_DIRECTION inout
  CONFIG.PCW_MIO_46_SLEW slow
  CONFIG.PCW_MIO_47_PULLUP enabled
  CONFIG.PCW_MIO_47_IOTYPE {LVCMOS 3.3V}
  CONFIG.PCW_MIO_47_DIRECTION inout
  CONFIG.PCW_MIO_47_SLEW slow
  CONFIG.PCW_MIO_48_PULLUP enabled
  CONFIG.PCW_MIO_48_IOTYPE {LVCMOS 3.3V}
  CONFIG.PCW_MIO_48_DIRECTION inout
  CONFIG.PCW_MIO_48_SLEW slow
  CONFIG.PCW_MIO_49_PULLUP enabled
  CONFIG.PCW_MIO_49_IOTYPE {LVCMOS 3.3V}
  CONFIG.PCW_MIO_49_DIRECTION inout
  CONFIG.PCW_MIO_49_SLEW slow
  CONFIG.PCW_MIO_50_PULLUP enabled
  CONFIG.PCW_MIO_50_IOTYPE {LVCMOS 3.3V}
  CONFIG.PCW_MIO_50_DIRECTION inout
  CONFIG.PCW_MIO_50_SLEW slow
  CONFIG.PCW_MIO_51_PULLUP enabled
  CONFIG.PCW_MIO_51_IOTYPE {LVCMOS 3.3V}
  CONFIG.PCW_MIO_51_DIRECTION inout
  CONFIG.PCW_MIO_51_SLEW slow
  CONFIG.PCW_MIO_52_PULLUP enabled
  CONFIG.PCW_MIO_52_IOTYPE {LVCMOS 3.3V}
  CONFIG.PCW_MIO_52_DIRECTION inout
  CONFIG.PCW_MIO_52_SLEW slow
  CONFIG.PCW_MIO_53_PULLUP enabled
  CONFIG.PCW_MIO_53_IOTYPE {LVCMOS 3.3V}
  CONFIG.PCW_MIO_53_DIRECTION inout
  CONFIG.PCW_MIO_53_SLEW slow
  CONFIG.PCW_MIO_TREE_PERIPHERALS {NAND Flash#GPIO#NAND Flash#NAND Flash#NAND Flash#NAND Flash#NAND Flash#NAND Flash#NAND Flash#NAND Flash#NAND Flash#NAND Flash#NAND Flash#NAND Flash#NAND Flash#GPIO#GPIO#GPIO#GPIO#GPIO#GPIO#GPIO#GPIO#GPIO#UART 1#UART 1#GPIO#GPIO#GPIO#GPIO#GPIO#GPIO#GPIO#GPIO#GPIO#GPIO#GPIO#GPIO#GPIO#GPIO#SD 0#SD 0#SD 0#SD 0#SD 0#SD 0#GPIO#GPIO#GPIO#GPIO#GPIO#GPIO#GPIO#GPIO}
  CONFIG.PCW_MIO_TREE_SIGNALS {cs#gpio[1]#ale#we_b#data[2]#data[0]#data[1]#cle#re_b#data[4]#data[5]#data[6]#data[7]#data[3]#busy#gpio[15]#gpio[16]#gpio[17]#gpio[18]#gpio[19]#gpio[20]#gpio[21]#gpio[22]#gpio[23]#tx#rx#gpio[26]#gpio[27]#gpio[28]#gpio[29]#gpio[30]#gpio[31]#gpio[32]#gpio[33]#gpio[34]#gpio[35]#gpio[36]#gpio[37]#gpio[38]#gpio[39]#clk#cmd#data[0]#data[1]#data[2]#data[3]#gpio[46]#gpio[47]#gpio[48]#gpio[49]#gpio[50]#gpio[51]#gpio[52]#gpio[53]}
}
# Vivado turns these on by itself once the peripherals above are enabled; the board design has them off.
# Applied in a second call, after PS7_PARAMS.
set PS7_PARAMS_LATE {
  CONFIG.PCW_ENET_RESET_ENABLE 0
  CONFIG.PCW_I2C_RESET_ENABLE 0
  CONFIG.PCW_USB_RESET_ENABLE 0
  CONFIG.PCW_MIO_34_DIRECTION in
}
